---
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
library(gapminder)
library(gganimate)
library(tidyverse)
```

```{r make_plot, cache=TRUE }
gapminder$continent=factor(gapminder$continent, levels = c("Americas","Africa","Asia"))

gapminder %>%
  mutate(continent = fct_collapse(continent,
                                  Americas = "Americas",
                                  Africa = "Africa",
                                  Asia = c("Asia", "Oceania"))) %>%
  filter(continent != "Europe") %>%
  ggplot(aes(x= gdpPercap, y = lifeExp, size = pop, color = country)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  facet_wrap(~continent) +
  scale_x_log10(breaks = c(1000,10000), labels = c("$1000", "10000")) +
  labs(x = "GDP Per Capita",
       y= "Life Expectancy",
       caption = "Gapminder Package") +
  scale_y_continuous(breaks = seq(40, 80, by= 20),
                     labels = c("40", "60", "80"),
                     limits = c(20, 85)) +
  scale_color_manual(values = country_colors) +
  transition_time(year) +
  labs(title= "The World Gets Better Every Year:{frame_time}")
  
  


```

```{r}
gapminder %>%
  filter(year == 1952) %>%
  ggplot(aes(x= gdpPercap, y = lifeExp)) + geom_point()
```

